# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170228_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mail',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=datetime.datetime(2017, 3, 11, 13, 11, 33, 884994, tzinfo=utc), max_length=80, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
