# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
