# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170312_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='Status')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('topped', models.BooleanField(default=False, verbose_name='Topped')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Category')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contactor', models.CharField(max_length=30, verbose_name='Name_Contactor')),
                ('email_contactor', models.EmailField(max_length=254, verbose_name='Email_Contactor')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
            ],
            options={
                'ordering': ['created_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client'),
        ),
    ]
