# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170316_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Tag')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Last Modified Time')),
            ],
        ),
    ]
