# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag', verbose_name='ensemble'),
        ),
    ]
